version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.8-management
    container_name: camel-ms--rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
  microservicea:
    image: thiagoandradeit/camelcourse-microservice-a:1.0
    container_name: camel-ms--microservice-a
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq